### ISSUE TITLE
Extract name and email separately

### ISSUE THREAD

**Issue by glennzw** [jordan-wright/email#114]
Is it possible to extract the sender name / email from an email object? I couldn't find an option for this in the documentation or code.

i.e from this:
```
e := &email.Email {
	From: "Jordan Wright <test@gmail.com>",
}
```

I'd like to extract "Jordan Wright" and "test@gmail.com" separately.

If not I'll just proceed with a regex, but wanted to check I wasn't missing something:

```
var r = regexp.MustCompile("^(.*)<(.*)>$")
e := r.FindStringSubmatch(e.From)
name := e[1]
email := e[2]
```

**Comment by jordan-wright** [comment]
I think https://golang.org/pkg/net/mail/#ParseAddress might be what you’re looking for. :)

**Comment by glennzw** [comment]
Whoops, right you are 🙈 Thanks!
