### ISSUE TITLE
NewEmailFromReader is not handling multiple To, Cc and Bcc addresses correctly

### ISSUE THREAD

**Issue by tarmo-randma** [jordan-wright/email#125]
In the current version NewEmailFromReader is not handling multiple To, Cc and Bcc addresses as expected.

Eg.
For header: To: Jordan Wright <jmwright798@gmail.com>, also@example.com
The API would return ["Jordan Wright <jmwright798@gmail.com>, also@example.com"] instead of the expected ["Jordan Wright <jmwright798@gmail.com>", "also@example.com"]

I have submitted https://github.com/jordan-wright/email/pull/124 to fix the issue

**Comment by jordan-wright** [comment]
Closed via 1d71dd29cc52dd6cf06e925b010fc8502ae95d57
