### ISSUE TITLE
Add Message-ID header

### ISSUE THREAD

**Issue by vdvm** [jordan-wright/email#13]
Hi,

I would like to request an enhancement. Can you add a Message-ID header?

http://tools.ietf.org/html/rfc5322
http://en.wikipedia.org/wiki/Message-ID

**Comment by njagadeesh** [comment]
According to RFC 822 and  2822 every email should have unique message-id in their header. I am a mutt user, I sort email by message-id which helps me sorting emails. suggestion made to have uuid-datetime@host-fqdn would be better or even we can use uuid-datetime-go-email@host-fqdn. I would love adding this feature

**Comment by jordan-wright** [comment]
Looks like this one got put on the back-burner, but it shouldn't be hard to implement. Let me see what I can do.

**Comment by jordan-wright** [comment]
After reviewing some options, I believe I will go with a format similar to that provided by Python's ```email``` package:

``` python
def make_msgid(idstring=None):
    """Returns a string suitable for RFC 2822 compliant Message-ID, e.g:

    <142480216486.20800.16526388040877946887@nightshade.la.mastaler.com>

    Optional idstring if given is a string used to strengthen the
    uniqueness of the message id.
    """
    timeval = int(time.time()*100)
    pid = os.getpid()
    randint = random.getrandbits(64)
    if idstring is None:
        idstring = ''
    else:
        idstring = '.' + idstring
    idhost = socket.getfqdn()
    msgid = '<%d.%d.%d%s@%s>' % (timeval, pid, randint, idstring, idhost)
    return msgid
```

**Comment by jordan-wright** [comment]
Ok, this should be good to go as of b359bc6. If you could please confirm, then I will consider this closed out.

If this still isn't working for you, please let me know and I'll re-open the issue.

Thanks for the great suggestion!
