### ISSUE TITLE
Emails with no body insert attachment as text.

### ISSUE THREAD

**Issue by krolaw** [jordan-wright/email#15]
I.E.

From: xxx@bigpond.com.au
Subject: Invoice from My Apartment Motel
Date: 11 December 2014 2:42:59 pm NZDT
To: Patrick@spongebob.com

Content-Type: application/octet-stream
Content-Disposition: attachment;
filename="Invoice 2474.PDF"
Content-Id: <Invoice 2474.PDF>
Content-Transfer-Encoding: base64

JVBERi0xLjQKJaqrrK0KNCAwIG9iago8PAovQ3JlYXRvciAoQXBhY2hlIEZPUCBWZXJzaW9uIDEu
MCkKL1Byb2R1Y2VyIC...

**Comment by cuonglm** [comment]
@krolaw Which server generates above email content?

Here's an example from postfix:

```
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="------------364886E9732896FFFA961C46"
Content-Language: en-US

This is a multi-part message in MIME format.
--------------364886E9732896FFFA961C46
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 7bit



--------------364886E9732896FFFA961C46
Content-Type: text/plain; charset=UTF-8;
 name="test.txt"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="test.txt"

MQo=
--------------364886E9732896FFFA961C46--
```

and it's parsed correctly after #89

**Comment by krolaw** [comment]
I don't believe it was from any server. Possibly output from the library itself, but don't quote me, it was over 5 years ago. I'm betting the issue has long been fixed, so I'm closing it now.
