### ISSUE TITLE
'Access for less secure apps' needs to be on

### ISSUE THREAD

**Issue by Gys** [jordan-wright/email#19]
The example will only work if 'Access for less secure apps' is turned on. Its off by default (at least for the new account that I created).
Setting can be changed here:
https://www.google.com/settings/security/lesssecureapps

**Comment by jordan-wright** [comment]
I don't believe there is anything I can do to fix this in ```email```. This is a gmail setting that does not allow (by default) for third-party applications to login to the email via smtp.

Good to know, though! I just use an application-specific password since I have 2fa setup (and you should, too!)

**Comment by MoacirSchmidt** [comment]
You may try "App Passwords"
