### ISSUE TITLE
Use gpokg.in for API versioning?

### ISSUE THREAD

**Issue by amoghe** [jordan-wright/email#20]
So you can have API stability and address issues like "change `email.NewEmail()` to `email.New()`" in the future?

Thoughts?

**Comment by jordan-wright** [comment]
Done! 

See: [http://gopkg.in/jordan-wright/email.v1](http://gopkg.in/jordan-wright/email.v1)

**Comment by jordan-wright** [comment]
And re: changing ```email.NewEmail()``` to ```email.New()```, since I have multiple types exported by the package, the recommended way to handle it is via ```NewT()```, where ```T``` is the type :smile:
