### ISSUE TITLE
How to insert a linebreak into plain text body?

### ISSUE THREAD

**Issue by tschundeee** [jordan-wright/email#21]
Hi I wanted to know how I can achieve a linebreak in plain text mails? This might be a more general plain text email question but maybe I have luck here. 

I want something similar to <br> in HTML "\r\n" doesn't work for me.

**Comment by Gys** [comment]
To format the body string I use something like `fmt.Sprintf("This is body text.\nNext line.\n")` which works well. I always use `\n` only although that should not matter.
If this does not work then maybe post some Go code here that does not produce the required output.

**Comment by tschundeee** [comment]
My bad. In my SendMail Method I used plain text as HTML if HTML text is not explicitly set. That's why it didn't work. But thx for helping.
