### ISSUE TITLE
Non-Ascii Header Support

### ISSUE THREAD

**Issue by jordan-wright** [jordan-wright/email#22]
Currently, there is no support for non-ascii characters in subject lines, or recipient/sender headers.

Here are some RFC's for reference:

[Message Header Extensions for Non-ASCII Text](https://tools.ietf.org/html/rfc2047)

Other references:

* [https://en.wikipedia.org/wiki/Unicode_and_email](https://en.wikipedia.org/wiki/Unicode_and_email)
* [https://en.wikipedia.org/wiki/MIME#Encoded-Word](https://en.wikipedia.org/wiki/MIME#Encoded-Word)

**Comment by ichinaski** [comment]
I took on this issue in https://github.com/jordan-wright/email/pull/14. Opinions?

**Comment by jordan-wright** [comment]
Closed via #14 - thanks @ichinaski!
