### ISSUE TITLE
Unrecognized import path "mime/quotedprintable"

### ISSUE THREAD

**Issue by jhnferraris** [jordan-wright/email#35]
I'm relatively new in Go. I'm getting this error when building the dependencies thru Capistrano in our server

    $ go get -u github.com/jordan-wright/email
        | package github.com/jordan-wright/email
	    imports mime/quotedprintable: unrecognized import path "mime/quotedprintable"

The dependencies are being installed through `depman`. I tried `godep` but still getting the same  error. Weird thing is I'm only getting the error when I'm deploying.  In my local machine it's working fine.

My `deps.json` is:

    {        
        "email": {
            "repo": "github.com/jordan-wright/email",
            "version": "",
            "type": "git"
        } 
     }

Any thoughts?

**Comment by jordan-wright** [comment]
Is all machines running go 1.5 or above? That issue happens when you're running a version <1.5.

Let me know if that fixes the issue!

**Comment by jhnferraris** [comment]
@jordan-wright Confirmed. Lib requires go 1.5 or above. Missed out the documentation. Thanks!
Closing this.

**Comment by jordan-wright** [comment]
It's worth noting that you can use the gopkg version in the meantime (version 1) that does not require 1.5. You will just miss out on some of the newer features like importing an email from a reader, etc.
