### ISSUE TITLE
Use of mime/quotedprintable makes the package 1.5-only

### ISSUE THREAD

**Issue by dvdplm** [jordan-wright/email#36]
See the 1.5 changelog: https://golang.org/doc/go1.5
Commit #e95df3c231e547e71f95ae0e21e10944bafa19a0 adds mime/quotedprintable which is a new addition to the standard lib.

**Comment by jordan-wright** [comment]
Hey David! I completely understand your concern.

For pre-1.5 I [recommend](https://github.com/jordan-wright/email#installation) to use the gopkg.in version 1, which supports pre 1.5, it just won't have the new features and fixes moving forward.

I hope this helps!

**Comment by dvdplm** [comment]
Hi Jordan,
That worked perfectly, thanks for the patience and I'll RTFM next time! :)
