### ISSUE TITLE
Attachment file name garbled

### ISSUE THREAD

**Issue by myml** [jordan-wright/email#43]
I think in the Content-Type followed by "; charset = utf-8"

**Comment by chenxuey** [comment]
I have the same problem. Have you solved it?

**Comment by myml** [comment]
Why I can not see you issues

2017-07-17 13:10 GMT+08:00 chenxuey <notifications@github.com>:

**Comment by chenxuey** [comment]
Yes,I deleted it  because I know your answer. 

> I think in the Content-Type followed by "; charset = utf-8"
