### ISSUE TITLE
Opportunistic TLS

### ISSUE THREAD

**Issue by wdingus** [jordan-wright/email#45]
We're getting this error when trying to send an email via a client's mail server:
x509: certificate is valid for {contents of LDAP/AD CN=___ here},

They advise that the server answering the connection on TCP:25 has a self-signed certificate and is using Opportunistic TLS. They say it is configured and performing correctly and our error is not the result of anything they will fix. We had also showed them that:

$ openssl s_client -connect {mail server}:25 -starttls smtp 2>&1 | openssl x509 -text -noout 2>&1 | grep DNS

Returns nothing from their mail server, but does from ours and various public mail servers around the internet.

Not sure if "Opportunistic TLS" is unsupported, or is even the issue at all... Any advice appreciated. Thanks.

**Comment by jordan-wright** [comment]
You'll want to use the `SendWithTLS` [function](https://godoc.org/github.com/jordan-wright/email#Email.SendWithTLS) and set a `tls.Config` that ignores SSL certificate validation, such as `&tls.Config{InsecureSkipVerify: true}`. That will allow connections to servers with self-signed certificates.

**Comment by maxisam** [comment]
We have the same issue. And it doesn't work. It throws error like tls: first record does not look like a TLS handshake
