### ISSUE TITLE
What's mean +4?

### ISSUE THREAD

**Issue by narita-takeru** [jordan-wright/email#49]
```
func (e *Email) msgHeaders() (textproto.MIMEHeader, error) {
	res := make(textproto.MIMEHeader, len(e.Headers)+4)
	if e.Headers != nil {
```

```
	res := make(textproto.MIMEHeader, len(e.Headers)+4)
```

Sorry, I Don't understood mean `+4`. 

Maybe, not need +4?

**Comment by lutzhorn** [comment]
As the comment says

https://github.com/jordan-wright/email/blob/4e83f7935625cb1802d4607962f4c4d86f877af0/email.go#L249

the four headers will be copied from the `Email` instance, if present there and not already included in `e.Headers`. Consider `e.Headers` being empty and the `Email` instance `e` having `e.To`, `e.From`, and `e.Subject`. To set them as headers, `res` must be large enough.
