### ISSUE TITLE
Sending without auth?

### ISSUE THREAD

**Issue by cemremengu** [jordan-wright/email#59]
One of our clients gave us an account on their SMTP server to send mails. However, it does not have any password so it fails all authentication methods (I tried PlainAuth which the server does not recognize and LoginAuth implementation which the server recognizes but fails to auth)

Is there a way for this kind of situations for bypassing the auth?

**Comment by cemremengu** [comment]
Apparently the server is using NTLM based auth. I am trying to implement one using the approach discussed [here](https://github.com/go-gomail/gomail/issues/16) for login auth and this [lib](https://github.com/Azure/go-ntlmssp) for NTLM over http.

Would you be interested in a PR @jordan-wright if I can successfully implement this?

**Comment by sp4ke** [comment]
I had the same issue, you just need to use

 `e.Send("localhost:<yourport>", smtp.PlainAuth("", "", "", "localhost"))`

**Comment by cemremengu** [comment]
Forgot to close 😄 

I solved this problem sometime ago with ` &tls.Config{InsecureSkipVerify: true}`
