### ISSUE TITLE
unexpected behavior for go 1.9.2

### ISSUE THREAD

**Issue by dongweigogo** [jordan-wright/email#60]
I use this package to send some emails in Chinese. When compiling with go 1.8.3, it's OK, but when compiling with go 1.9.2, the content seems to be encoded (I'm not sure, something like: =E5=86=85=E5=AE=B9)

Is there any easy solution to this?

**Comment by dongweigogo** [comment]
well, after a closer look, I found it's not related to go version, but to this package itself, because when I compile with previous source code of this package, it's also OK. 
Thus, the issue must come from some commit or updating.

**Comment by jordan-wright** [comment]
Can you provide an example of code that causes the issue, as well as what you see as the result, and what you expected to see?

**Comment by dongweigogo** [comment]
my code for sending email:

`func SendMail(hostport, from, password, to, subject, text string, html []byte) error {
        var e = email.NewEmail();
        e.From = from;
        e.To=strings.Split(to, ",");
        e.Subject = subject;
        e.Text =[]byte(text);
        e.HTML = html;
        var auth=smtp.PlainAuth("", from, password, strings.Split(hostport, ":")[0]);
        return e.Send(hostport, auth);
}`

When I send a email with the text content "测试邮件" (which means: testing email), the received content is : =E6=B5=8B=E8=AF=95=E9=82=AE=E4=BB=B6

**Comment by jordan-wright** [comment]
This has been fixed in #62. Thanks for the report!
