### ISSUE TITLE
TLS error with email 3

### ISSUE THREAD

**Issue by edgesoft** [jordan-wright/email#71]
TLS worked in 2.2 and now I get `first record does not look like a TLS handshake`

Comes from https://golang.org/src/crypto/tls/conn.go row 635

```javascript
plainAuth := smtp.PlainAuth("", mail.username, mail.password, mail.host)
if len(mail.username) == 0 {
  plainAuth = nil
}

err = e.SendWithTLS(fmt.Sprintf("%s:%s", mail.host, mail.smtpPort), plainAuth, &tls.Config{InsecureSkipVerify: true})

```

Any pointers?

**Comment by edgesoft** [comment]
Reverting the changes in SendWithTLS made it work again.

**Comment by StefanFransen** [comment]
Having the same issue, any updates?

**Comment by edgesoft** [comment]
@StefanFransen We had to fork it and go back to prior implementation

**Comment by AlexBBBril** [comment]
This problem occurs because if you use SMTP, you need to use a simple connection and send the "STARTTLS" signal to the server. This will tell the server includes tls and the to encrypt following packets in the connection. 

https://www.limilabs.com/blog/ssl-vs-tls-vs-starttls-stls

**Comment by wechatshop** [comment]
There is error " 454 Command not permitted when TLS active" when using  SendWithTLS　with port 465。

**Comment by victorcoder** [comment]
Any update on this issue? Thanks

**Comment by SteelPhase** [comment]
I'm running into this issue as well. SendWithTLS might need to be broken up to handle STARTTLS, vs a tls connection. SendWithTLS is definitely not correct in the latest version
