### ISSUE TITLE
Too many login attempts

### ISSUE THREAD

**Issue by NoelHG** [jordan-wright/email#99]
I'm getting the error "too many login attempts"

is that due to limits on my gmail smtp server or is the pool of reusable connections not working?

**Comment by jordan-wright** [comment]
Without example code, it's hard to say- it could be either.

You can find more information about email sending limits for Gmail [here](https://support.google.com/a/answer/176600?hl=en) and [here](https://support.google.com/a/answer/166852).

If you have example code that reproduces the problem, I'll reopen this and we can investigate further. In the meantime, I'm going to close this one out.
